### ISSUE TITLE
Encountered Rhino & PhantomJS exceptions in the "Supporting the DOM" section of the current basic tutorial

### ISSUE THREAD

**Issue by byron-dupreez** [scala-js/scala-js#2323]
I ran into the following Rhino & PhantomJS exceptions in the "Supporting the DOM" section of the basic Scala.js tutorial at https://www.scala-js.org/tutorial/basic/:

Using PhantomJS, "run" gives the following error:

```
TypeError: undefined is not a function (evaluating '(0, $m_Lorg_scalajs_jquery_package$().jQuery$1)("body")')
  phantomjs://code/phantomjs-launcher307878747601157977.js:9 in onError
  phantomjs://code/phantomjs-launcher307878747601157977.js:11 in onError
  file:///home/byron/projects/scala-js-scratchpad/target/scala-2.11/scala-js-scratchpad-fastopt.js:2361 (in function "main__V")
  phantomjs://code/phantomjs-launcher307878747601157977.js:13
  file:///home/byron/projects/scala-js-scratchpad/target/scala-2.11/scala-js-scratchpad-fastopt.js:2366 (in function "$$js$exported$meth$main__O")
  phantomjs://code/phantomjs-launcher307878747601157977.js:13
  file:///home/byron/projects/scala-js-scratchpad/target/scala-2.11/scala-js-scratchpad-fastopt.js:2369 (in function "main")
  phantomjs://code/phantomjs-launcher307878747601157977.js:13
  file:///tmp/phantomjs-launcher-webpage2807197546191871915.html:63
  phantomjs://code/phantomjs-launcher307878747601157977.js:13
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: PhantomJS exited with code 2
    at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:110)
    at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:159)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
```

Executing "last" displays:

```
[info] Running tutorial.webapp.TutorialApp
[debug] with JSEnv ExternalJSEnv for PhantomJS
[debug] PhantomJS using webpage launcher at: /tmp/phantomjs-launcher-webpage2961836043432289371.html
[debug] PhantomJS using launcher at: /tmp/phantomjs-launcher780769038542239022.js
[debug] Starting process: phantomjs /tmp/phantomjs-launcher780769038542239022.js
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: PhantomJS exited with code 2
    at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:110)
    at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:159)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: PhantomJS exited with code 2
```

Attempting to use Rhino instead, gives similar error on "run":

```
[info] Running tutorial.webapp.TutorialApp
org.mozilla.javascript.EcmaError: TypeError: org.mozilla.javascript.Undefined@15aeb95d is not a function, it is undefined. (Ltutorial_webapp_TutorialApp$.sjsir#17)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3701)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3679)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3707)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3726)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3781)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3769)
    at org.mozilla.javascript.ScriptRuntime.getValueFunctionAndThis(ScriptRuntime.java:2297)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1335)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3102)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
    at org.mozilla.javascript.Context.evaluateString(Context.java:1078)
    at org.scalajs.jsenv.rhino.package$ContextOps$.evaluateFile$extension(package.scala:21)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:211)
    at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:87)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Exception while running JS code: TypeError: org.mozilla.javascript.Undefined@15aeb95d is not a function, it is undefined. (Ltutorial_webapp_TutorialApp$.sjsir#17)
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:227)
    at org.scalajs.jsenv.rhino.RhinoJSEnv$Runner.run(RhinoJSEnv.scala:87)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:639)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:699)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$56$$anonfun$apply$40$$anonfun$apply$41.apply(ScalaJSPluginInternal.scala:693)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Exception while running JS code: TypeError: org.mozilla.javascript.Undefined@15aeb95d is not a function, it is undefined. (Ltutorial_webapp_TutorialApp$.sjsir#17)
```

**Workaround for this error:**

Switch jquery library dependency back to older 0.8.0 version (instead of the recommended 0.9.0):

```
libraryDependencies += "be.doeraene" %%% "scalajs-jquery" % "0.8.0"
```

It would be great if this issue can be resolved, so that this workaround can be avoided.

**Comment by sjrd** [comment]
@byron-dupreez Did you add
```scala
jsDependencies +=
  "org.webjars" % "jquery" % "2.1.4" / "2.1.4/jquery.js"
```
in your `build.sbt` during "Step 5: Using jQuery"?

**Comment by sjrd** [comment]
Closing until there's some follow up.

**Comment by byron-dupreez** [comment]
Hi Sebastien,

Sorry for the delayed reply. I didn't necessarily want to go the route of
packaging all js dependencies into a single script and was also under the
impression that this was an optional step.

Nevertheless, I just attempted your suggestion (and switched back to jquery
0.9.0) and now I unfortunately have 2 errors in my html page:

1.  TutorialApp.scala:19Uncaught TypeError: (0 ,
$m_Lorg_scalajs_jquery_package$(...).jQuery$1) is not a
function$c_Ltutorial_webapp_TutorialApp$.main__V @
TutorialApp.scala:19$c_Ltutorial_webapp_TutorialApp$.$$js$exported$meth$main__O
@ JSApp.scala:18$c_Ltutorial_webapp_TutorialApp$.main @
TutorialApp.scala:15(anonymous function) @ scala-js-scratchpad-launcher.js:2


2.  GET http://localhost:63342/scala-js-scratchpad/*root*/target/scala-2.11/scala-js-tutorial-jsdeps.js

     Note that my basic project does NOT contain a "*root*" sub-folder, but
this is probably a side-effect of attempting:

lazy val root = (project in file(".")).
  enablePlugins(ScalaJSPlugin).
  settings(
    name := "scala-js-scratchpad",
    version := "1.0",
    scalaVersion := "2.11.8"
  )

which I added in an attempt to avoid "Expression type DslEntry must conform
to Def.SettingsDefinition in SBT file" error in Idea.

I managed to get my html page at least working again by:
1. Reverting my html page back to using <script type="text/javascript" src="
http://cdn.jsdelivr.net/jquery/2.2.2/jquery.js"></script>
2. Commenting out 
3. Reverting my build.sbt back to using:  libraryDependencies +=
"be.doeraene" %%% "scalajs-jquery" % "0.8.0"
4. Commenting out the following:
    //skip in packageJSDependencies := false
    //jsDependencies += "org.webjars" % "jquery" % "2.1.4" /
"2.1.4/jquery.js"

So I was back to square one.
This worked:
    libraryDependencies += "be.doeraene" %%% "scalajs-jquery" % "0.8.0"
This did not work:
    libraryDependencies += "be.doeraene" %%% "scalajs-jquery" % "0.9.0" //
triggers org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: PhantomJS
exited with code 2

I then reverted the lazy val root "fix" above back to the Basic Tutorial's
version (which gives the IDEA error) and lo and behold, now the page seems
to work with scalajs-query 0.9.0 in build.sbt too (without the webjars
changes).

**Comment by SeriousSoftware** [comment]
Hi all,

I had the same experience but in a couple of browsers (Chrome, Edge and Firefox). When I have configured for 0.9.0 they report all ` Uncaught TypeError: (0 , $m_Lorg_scalajs_jquery_package$(...).jQuery$1) is not a function. So I have to use 0.8.1.

Probably has byron-dupreez forgotten to reload sbt and thinks it worked on version 0.9.0 which is not the case.

Thank you for your attention.

**Comment by cuevash** [comment]
Hi all ,

Same problem here. 

Using this on the <head>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet-src.js"></script>
    <script src="//cdn.jsdelivr.net/pouchdb/6.0.7/pouchdb.min.js"></script>

and being this my sbt:

enablePlugins(ScalaJSPlugin)

// Leaflet facade

resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
libraryDependencies += "io.plasmap" %%% "pamphlet" % "0.9-SNAPSHOT"


// Leaflet facade

scalaJSUseRhino in Global := false

skip in packageJSDependencies := false

libraryDependencies += "be.doeraene" %%% "scalajs-jquery" % "0.8.1"

//jsDependencies += "org.webjars" % "jquery" % "2.1.4" / "2.1.4/jquery.js"

jsDependencies += RuntimeDOM

// REACT Libs
// core = essentials only. No bells or whistles.
libraryDependencies += "com.github.japgolly.scalajs-react" %%% "core" % "0.11.2"

// React JS itself (Note the filenames, adjust as needed, eg. to remove addons.)
jsDependencies ++= Seq(

  "org.webjars.bower" % "react" % "15.3.2"
    /        "react-with-addons.js"
    minified "react-with-addons.min.js"
    commonJSName "React",

  "org.webjars.bower" % "react" % "15.3.2"
    /         "react-dom.js"
    minified  "react-dom.min.js"
    dependsOn "react-with-addons.js"
    commonJSName "ReactDOM",

  "org.webjars.bower" % "react" % "15.3.2"
    /         "react-dom-server.js"
    minified  "react-dom-server.min.js"
    dependsOn "react-dom.js"
    commonJSName "ReactDOMServer")


libraryDependencies += "com.lihaoyi" %%% "utest" % "0.3.0" % "test"
testFrameworks += new TestFramework("utest.runner.Framework")


//Pouchdb dependencies
libraryDependencies += "com.github.chandu0101.scalajs" %%% "pouchdb" % "2016.8.0"

persistLauncher in Compile := true

persistLauncher in Test := false

// Main class of the APP
mainClass in Compile := Some("sgfct.main_web.MainWeb")

name := "TestScala_js"

version := "1.0"

scalaVersion := "2.11.8"

I was having the same problem.

So I have to use 0.8.1. It works. It maybe related to the colusion of the jquery version.. that is included maybe in some of the other libs..?

**Comment by sjrd** [comment]
With scalajs-jquery 0.9.0, you need this line to be enabled in build.sbt:
```scala
jsDependencies += "org.webjars" % "jquery" % "2.1.4" / "2.1.4/jquery.js"
```
to be able to run from sbt.

**Comment by sjrd** [comment]
Closing, as this seems to work as intended.
