### ISSUE TITLE
2.13 ListBuffer clone breaks Vector

### ISSUE THREAD

**Issue by jpriddey** [scala-js/scala-js#3778]
Repeatable with Scala 2.13.1 and Scala.js 0.6.29

Making use of `ListBuffer.clone` changes the generated JS code and breaks Vector:

Here's the simplified test case:
```scala
import org.scalatest.FunSuite

import scala.collection.mutable.ListBuffer

class UseVector extends FunSuite{
  test("listbuffer clone") {
    val buffer = new ListBuffer[Int]
    buffer.clone
  }

  test("update") {
    val v1 = Vector(0,1,2,3)
    val v2 = v1.updated(2,9)
    assert(v2 === Vector(0,1,9,3))
  }
}
```
Comment out `buffer.clone` and the tests pass. Include `buffer.clone` and the second test fails with
```
[info]   scala.scalajs.js.JavaScriptException: TypeError: $thiz.newSpecificBuilder__scm_Builder is not a function
[info]   at scala.collection.mutable.SeqOps.clone(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:52347:17)
[info]   at scala.collection.immutable.VectorPointer.gotoPosWritable0(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:2299:49)
[info]   at scala.collection.immutable.Vector.gotoPosWritable(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:70389:5)
[info]   at scala.collection.immutable.Vector.updateAt(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:70803:5)
[info]   at {anonymous}()(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:63179:19)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:34310:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:1405:7)
[info]   at org.scalatest.Transformer.apply(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:40944:10)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:35429:72)
[info]   at org.scalatest.FunSuiteLike.invokeWithFixture$1(/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-test-fastopt.js:61463:15)
```
This seems to be due to different code generated in `VectorPointer` depending on whether clone is used:
```js
$thiz.display0$und$eq__AO__V($asArrayOf_O($thiz.display0__AO().clone__O(), 1));
```
```js
$thiz.display0$und$eq__AO__V($asArrayOf_O($f_scm_SeqOps__clone__O(this$6), 1));
```
The first works, the second fails inside `SeqOps__clone` with "is not a function" as shown above.

This use of `ListBuffer` `clone` worked correctly in Scala 2.12.9 and Scala.js 0.6.28.

**Comment by sjrd** [comment]
Hello, and thanks for the report.

You say that you switch from Scala 2.12.9/Scala.js 0.6.28 to Scala 2.13.1/Scala.js 0.6.29. Could you identify whether it's the Scala 2.12.9 -> 2.13.1 upgrade that causes the issue or whether it's the Scala.js 0.6.28 -> 0.6.29 upgrade that does? What about 2.13.0?

Could you make a reproduction that does not depend on ScalaTest? Ideally as a simple `def main(args: Array[String]): Unit`?

**Comment by jpriddey** [comment]
Thanks for looking into this. 

My guess is that it is related to the introduction of SeqOps in 2.13. I just tried reverting my test to 0.6.28 and the problem remained. 

Here's a standalone example (with scalaJSUseMainModuleInitializer := true)

import scala.collection.mutable.ListBuffer

object RunMain {
  def main(args: Array[String]): Unit = {
    val buffer = new ListBuffer[Int]
    buffer.clone
    val v1 = Vector(0,1,2,3)
    val v2 = v1.updated(2,9)
    println(v2 == Vector(0,1,9,3))
  }
}

and you should be able to reproduce the error. 

[info] Running RunMain
/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-fastopt.js:9207
  var b = $thiz.newSpecificBuilder__scm_Builder();
                ^

TypeError: $thiz.newSpecificBuilder__scm_Builder is not a function
    at $f_scm_SeqOps__clone__O (/home/jon/Code/Jon/JSError/target/scala-2.13/classes/js/js-error-fastopt.js:9207:17)
etc.

**Comment by sjrd** [comment]
Thanks for the reproduction. I can indeed reproduce the issue in 0.6.x and 1.x.

This is caused by the optimizer wrongly inlining `.clone__O()` on an array. It thinks that the only (reachable) implementation of `clone__O` is in `SeqOps`, so it inlines that method, which of course is wrong for an array. The reason this can happen is that `clone__O` for arrays has a very special treatment in the linker: it is the only method that has an actual implementation in the array classes (as opposed to the one inherited from `Object`), but array classes are never defined in IR form (they are "VM-generated").

Workaround 1: disable the optimizer with
```scala
scalaJSLinkerConfig ~= { _.withOptimizer(false) }
```
in the sbt `settings()` of the project.

Workaround 2: super ugly but useful if you want to keep the optimizer: add the following code somewhere in reachable code (e.g. your `main` method, but then you also need it in one of your tests probably):
```scala
class WorkaroundBug3778 {
  override def clone(): Object = new WorkaroundBug3778
}
new WorkaroundBug3778().clone()
```
This causes a *second* possible `clone__O` method to be reachable in the codebase, which prevents the optimizer from inlining the one from `SeqOps` on an array.

**Comment by sjrd** [comment]
Fixed for 0.6.x in 38decc1b4b7091326f880a35efcf5302c5cc881d.
