### ISSUE TITLE
 Found unknown label apply at 

### ISSUE THREAD

**Issue by tgodzik** [scala-js/scala-js#5112]
When compiling Scala JS version of trees I am getting

```
[info] compiling 78 Scala sources to /home/runner/work/scalameta/scalameta/scalameta/trees/js/target/scala-2.13/classes ...
[error] Found unknown label apply at source-/home/runner/work/scalameta/scalameta/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala,line-563,offset=18279: default8()
[error] Error while emitting LegacyScanner.scala
[error] Found unknown label apply at source-/home/runner/work/scalameta/scalameta/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala,line-563,offset=18279: default8()
[error] two errors found
[error] (treesJS / Compile / compileIncremental) Compilation failed
```

I tried both 1.17.0 and 1.18.1 with Scala 2.13.16

More info here https://github.com/scalameta/scalameta/actions/runs/12724233513/job/35470181732

I tried minimizing, but I can't seem to reproduce on a smaller snippet.

**Comment by tgodzik** [comment]
Doing:
`scalaJSLinkerConfig := StandardConfig().withBatchMode(true).withOptimizer(false).withCheckIR(true)`
doesn't seem to change anything.

**Comment by sjrd** [comment]
That doesn't even reach the IR checker. It's a crash in the compiler backend.

Are there macros involved?

**Comment by tgodzik** [comment]
> Are there macros involved?

Not in that class, but we do have some macros mostly for code generation in that module. 
> Can you minimize that method and possibly then decouple it from the rest of the code?

```
//> using platform js
//> using scala 2.13.16
//> using jsVersion 1.17.0

import scala.annotation.switch
import scala.annotation.tailrec

class LegacyScanner {

  var ch: Char = 'a'

  @scala.annotation.tailrec
  private def getStringPart(multiLine: Boolean): Unit = {

    if (multiLine) { getStringPart(multiLine) }
    else
      (ch: @switch) match {
        case '\\' if !multiLine        =>
        case '\n' | '\r' if !multiLine =>
        case _                         =>
      }
  }

}
```

this seems to fail still

**Comment by sjrd** [comment]
I can indeed reproduce on `main` with 2.13.16, whereas it works with 2.13.15. Scala 2.13.16 definitely changed something to the way it translates pattern matching, and now we have a new shape to handle.

Scala 2.13.15 produced:
```scala
package helloworld {
  class LegacyScanner extends Object {
    private[this] var ch: Char = _;
    <accessor> def ch(): Char = LegacyScanner.this.ch;
    <accessor> def ch_=(x$1: Char): Unit = LegacyScanner.this.ch = x$1;
    @scala.annotation.tailrec private def getStringPart(multiLine: Boolean): Unit = {
      <synthetic> val _$this: helloworld.LegacyScanner = LegacyScanner.this;
      _getStringPart(_$this: helloworld.LegacyScanner, multiLine: Boolean){
        (if (multiLine)
          {
            _getStringPart(LegacyScanner.this, (multiLine: Boolean));
            scala.runtime.BoxedUnit.UNIT
          }
        else
          {
            case <synthetic> val x1: Char = (LegacyScanner.this.ch(): Char);
            (x1.toInt(): Int) match {
              case 92 => if (multiLine.unary_!())
                scala.runtime.BoxedUnit.UNIT
              else
                {
                  default5();
                  scala.runtime.BoxedUnit.UNIT
                }
              case (10| 13) => if (multiLine.unary_!())
                scala.runtime.BoxedUnit.UNIT
              else
                {
                  default5();
                  scala.runtime.BoxedUnit.UNIT
                }
              case _ => default5(){
                scala.runtime.BoxedUnit.UNIT
              }
            }
          }: scala.runtime.BoxedUnit);
        ()
      }
    };
    def <init>(): helloworld.LegacyScanner = {
      LegacyScanner.super.<init>();
      LegacyScanner.this.ch = 'a';
      ()
    }
  }
}
```
Scala 2.13.16 produced:
```scala
package helloworld {
  class LegacyScanner extends Object {
    private[this] var ch: Char = _;
    <accessor> def ch(): Char = LegacyScanner.this.ch;
    <accessor> def ch_=(x$1: Char): Unit = LegacyScanner.this.ch = x$1;
    @scala.annotation.tailrec private def getStringPart(multiLine: Boolean): Unit = {
      <synthetic> val _$this: helloworld.LegacyScanner = LegacyScanner.this;
      _getStringPart(_$this: helloworld.LegacyScanner, multiLine: Boolean){
        (if (multiLine)
          _getStringPart(LegacyScanner.this, (multiLine: Boolean)).$asInstanceOf[scala.runtime.BoxedUnit]()
        else
          {
            case <synthetic> val x1: Char = (LegacyScanner.this.ch(): Char);
            (x1.toInt(): Int) match {
              case 92 => if (multiLine.unary_!())
                scala.runtime.BoxedUnit.UNIT
              else
                default5().$asInstanceOf[scala.runtime.BoxedUnit]()
              case (10| 13) => if (multiLine.unary_!())
                scala.runtime.BoxedUnit.UNIT
              else
                default5().$asInstanceOf[scala.runtime.BoxedUnit]()
              case _ => default5(){
                scala.runtime.BoxedUnit.UNIT
              }
            }
          }: scala.runtime.BoxedUnit);
        ()
      }
    };
    def <init>(): helloworld.LegacyScanner = {
      LegacyScanner.super.<init>();
      LegacyScanner.this.ch = 'a';
      ()
    }
  }
}
```
Diff:
```diff
--- bug-mixin-2.13.15.scala	2025-01-11 18:05:58.230606200 +0100
+++ bug-mixin-2.13.16.scala	2025-01-11 18:04:28.541076900 +0100
@@ -7,10 +7,7 @@
       <synthetic> val _$this: helloworld.LegacyScanner = LegacyScanner.this;
       _getStringPart(_$this: helloworld.LegacyScanner, multiLine: Boolean){
         (if (multiLine)
-          {
-            _getStringPart(LegacyScanner.this, (multiLine: Boolean));
-            scala.runtime.BoxedUnit.UNIT
-          }
+          _getStringPart(LegacyScanner.this, (multiLine: Boolean)).$asInstanceOf[scala.runtime.BoxedUnit]()
         else
           {
             case <synthetic> val x1: Char = (LegacyScanner.this.ch(): Char);
@@ -18,17 +15,11 @@
               case 92 => if (multiLine.unary_!())
                 scala.runtime.BoxedUnit.UNIT
               else
-                {
-                  default5();
-                  scala.runtime.BoxedUnit.UNIT
-                }
+                default5().$asInstanceOf[scala.runtime.BoxedUnit]()
               case (10| 13) => if (multiLine.unary_!())
                 scala.runtime.BoxedUnit.UNIT
               else
-                {
-                  default5();
-                  scala.runtime.BoxedUnit.UNIT
-                }
+                default5().$asInstanceOf[scala.runtime.BoxedUnit]()
               case _ => default5(){
                 scala.runtime.BoxedUnit.UNIT
               }
```
