### ISSUE TITLE
Compilation failure (IdentityHashMap) on recent Scala 2.13.2 nightly

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#3792]
at e.g. https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/2658/artifact/logs/scala-js-build.log we see:

```
[scala-js] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/scala-js-7654802acae1122fadcbca880b40e51c7700e137/javalib/src/main/scala/java/util/IdentityHashMap.scala:43: error: ambiguous reference to overloaded definition,
[scala-js] [error] both constructor IdentityHashMap in class IdentityHashMap of type (initialMap: java.util.Map[_ <: K, _ <: V])java.util.IdentityHashMap[K,V]
[scala-js] [error] and  constructor IdentityHashMap in class IdentityHashMap of type (inner: java.util.HashMap[java.util.IdentityHashMap.IdentityBox[K],V])java.util.IdentityHashMap[K,V]
[scala-js] [error] match argument types (java.util.HashMap[java.util.IdentityHashMap.IdentityBox[K],V]) and expected result type AnyRef
[scala-js] [error]     new IdentityHashMap(
[scala-js] [error]     ^
```

Scala version is 2.13.2-bin-59dec61

**Comment by sjrd** [comment]
I've minimized it down to the following test file:
```scala
package test

trait Map[K, V]

class HashMap[K, V] extends Map[K, V] {
  override def clone(): AnyRef = super.clone()
}

class IdentityBox[+A]

class IdentityHashMap[K, V](inner: HashMap[IdentityBox[K], V])
    extends Map[K, V] {

  def this(initialMap: Map[_ <: K, _ <: V]) =
    this(new HashMap[IdentityBox[K], V]())

  override def clone(): AnyRef = {
    new IdentityHashMap(
        inner.clone().asInstanceOf[HashMap[IdentityBox[K], V]])
  }
}
```
It compiles fine in 2.13.0, but fails to compile in 2.13.1.
