### ISSUE TITLE
implicit classes in 0.6.4

### ISSUE THREAD

**Issue by brianwawok** [scala-js/scala-js#1864]
Did something wacky happen to implicit classes in 0.6.4?

I have some global library that adds itself to global scope.. adds a .wizard() method to things. Cool. So I had code like this:

```scala
object WizardImplicits {

  implicit class JQueryWizardable(obj : JQuery) extends Wizardable

}


sealed trait Wizardable extends JQuery {

  def wizard() : WizardDataable = js.native

}
```

This worked in 0.6.3.  In 0.6.4, in some browsers (Chrome for sure), I started getting 

```
Uncaught TypeError: p.WizardImplicits$JQueryWizardable is not a function
```

Not exactly sure why?  I changed the code to be

```scala
object WizardImplicits {

  import scala.language.implicitConversions

  implicit def JQueryIsWizardable(obj : JQuery) : Wizardable =  obj.asInstanceOf[Wizardable]

}


sealed trait Wizardable extends JQuery {

  def wizard() : WizardDataable = js.native

}
```

And all is well again. Was my old code "wrong"?  It compiled fine in all cases, but blew up at runtime in 0.6.4 on chrome.

**Comment by sjrd** [comment]
Your old code was wrong indeed.

`implicit class` in Scala is syntactic sugar for a class and an `implicit def`. So your former code is syntactic sugar for this:
```scala
object WizardImplicits {
  class JQueryWizardable(obj: JQuery) extends Wizardable

  implicit def JQueryWizardable(obj: JQuery): Wizardable =
    new Wizardable(obj)
}
```
but since `JQueryWizardable` extends `Wizardable`, it transitively inherits from `js.Any` and is therefore a facade type. The Scala.js compiler therefore thinks (because you told it so) that there is a native class named `WizardImplicits$JQueryWizardable` in the global scope. This is false, of course, hence the `TypeError`.

I have no idea how that could have ever worked with 0.6.3, though ^^ The same reasoning has applied since, phfew, 0.1-SNAPSHOT, I think :p

**Comment by brianwawok** [comment]
I have no idea either but it worked.... hum
