### ISSUE TITLE
type WasPublicBeforeTyper is not a member of package scala.scalajs.js.annotation

### ISSUE THREAD

**Issue by ashawley** [scala-js/scala-js#4055]
After upgrading to 1.1.0, the build for ScalaCheck gave the following error:
```
[error] /home/travis/build/typelevel/scalacheck/js/target/scala-2.13/src_managed/main/org/scalacheck/GenArities.scala:268:20: type WasPublicBeforeTyper is not a member of package scala.scalajs.js.annotation
[error]     g1.flatMap(new Function1[T1, Gen[(T1,T2)]] { def apply(t1: T1): Gen[(T1,T2)] = g2.map { t2 => (t1, t2) } })
[...]
[error] 100 errors found
```

The generated code that it's choking on is:

```scala
  /** Combines the given generators into one generator that produces a
   *  tuple of their generated values. */
  def zip[T1,T2](
    g1:Gen[T1], g2:Gen[T2]
  ): Gen[(T1,T2)] = {
    val g = g1.flatMap(new Function1[T1, Gen[(T1,T2)]] { def apply(t1: T1): Gen[(T1,T2)] = g2.map { t2 => (t1, t2) } })
    g.suchThat {
      case (t1, t2) =>
        g1.sieveCopy(t1) && g2.sieveCopy(t2)
    }
  }
```

Here's the PR and an example failing Travis build:

https://github.com/typelevel/scalacheck/pull/659
https://travis-ci.org/github/typelevel/scalacheck/jobs/686728878

**Comment by sjrd** [comment]
It's in `scala.scalajs.js.annotation.internal` now:
https://github.com/scala-js/scala-js/tree/master/library/src/main/scala/scala/scalajs/js/annotation/internal

Do you have a macro that for some reason tries to access that thing?

**Comment by ashawley** [comment]
No, not to my knowledge.

**Comment by sjrd** [comment]
When you say "The generated code that it's choking on is:", is that macro-generated? Or is it a generated source file?

What macros and/or compiler plugins are at play in that codebase? Can you reproduce in an environment that has no macro nor compiler plugin?

**Comment by sjrd** [comment]
There's something broken in your build: you're using Scala.js 1.1.0 but you have the 0.6.32 compiler plugin:
```
sbt:scalacheck> show js/compile:dependencyClasspath
[info] * Attributed(...\org\scala-lang\scala-library\2.13.1\scala-library-2.13.1.jar)
[info] * Attributed(...\org\scala-js\scalajs-library_2.13\1.1.0\scalajs-library_2.13-1.1.0.jar)
[info] * Attributed(...\org\scala-js\scalajs-test-interface_2.13\1.1.0\scalajs-test-interface_2.13-1.1.0.jar)

sbt:scalacheck> show js/compile:scalacOptions
[info] * -encoding
[info] * UTF-8
[info] * -feature
[info] * -unchecked
[info] * -Ywarn-dead-code
[info] * -Ywarn-numeric-widen
[info] * -Xlint:-unused
[info] * -Ywarn-unused:-patvars,-implicits,-locals,-privates,-explicits
[info] * -Xplugin:...\org\scala-js\scalajs-compiler_2.13.1\0.6.32\scalajs-compiler_2.13.1-0.6.32.jar
```
So yeah, the compiler plugin of 0.6.32 tries to get a reference to `scala.scalajs.js.annotation.WasPublicBeforeTyper`, for its internal usage, but it can't find it because on the classpath you've got `scalajs-library` v1.1.0.

**Comment by sjrd** [comment]
See here for the fix: https://github.com/typelevel/scalacheck/pull/659#pullrequestreview-414602884

**Comment by ashawley** [comment]
Ok, sorry about that.  I should have tinkered  around with it further.
