### ISSUE TITLE
Adapt to Scala 2.12 trait encoding (removal of impl classes)

### ISSUE THREAD

**Issue by retronym** [scala-js/scala-js#2285]
We've just run a community build against my pull request, https://github.com/scala/scala/pull/5003, that changes the Scala 2.12 trait encoding.

I was pleasantly surprised to find that everything worked... well everything other than Scala JS.

Here are the compile failure, related to methods I've removed about impl classes.

```
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:240: value IMPL_CLASS_SUFFIX is not a member of object GenJSCode.this.global.nme
[scala-js] [error]                 sym.owner.info.decl(sym.name.dropRight(nme.IMPL_CLASS_SUFFIX.length)).tpe)
[scala-js] [error]                                                            ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:240: value IMPL_CLASS_SUFFIX is not a member of object GenJSCode.this.global.nme
[scala-js] [error]                 sym.owner.info.decl(sym.name.dropRight(nme.IMPL_CLASS_SUFFIX.length)).tpe)
[scala-js] [error]                                                            ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:1056: value implClass is not a member of GenJSCode.this.global.Symbol
[scala-js] [error]             val implClassSym = sym.owner.implClass
[scala-js] [error]                                          ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:1056: value implClass is not a member of GenJSCode.this.global.Symbol
[scala-js] [error]             val implClassSym = sym.owner.implClass
[scala-js] [error]                                          ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala:189: value isImplClassName is not a member of object JSEncoding.this.global.nme
[scala-js] [error]     sym.isModuleClass && nme.isImplClassName(sym.name)
[scala-js] [error]                              ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala:189: value isImplClassName is not a member of object JSEncoding.this.global.nme
[scala-js] [error]     sym.isModuleClass && nme.isImplClassName(sym.name)
[scala-js] [error]                              ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/TypeKinds.scala:238: value interfaceName is not a member of object TypeKinds.this.global.tpnme
[scala-js] [error]         val traitSym = sym.owner.info.decl(tpnme.interfaceName(sym.name))
[scala-js] [error]                                                  ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/TypeKinds.scala:238: value interfaceName is not a member of object TypeKinds.this.global.tpnme
[scala-js] [error]         val traitSym = sym.owner.info.decl(tpnme.interfaceName(sym.name))
[scala-js] [error]                                                  ^
```

You can experiment with this build with [2.12.0-03cc6f9-SNAPSHOT](https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.12.0-03cc6f9-SNAPSHOT/) from `"pr-scala snapshots" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"`

Would you be willing to adapt to these changes on a 2.12.x branch of ScalaJS?

**Comment by sjrd** [comment]
Sure, I'll work on this today. We already have default methods in the IR and the linker, so it's only the compiler plugin that needs some work.

**Comment by sjrd** [comment]
@retronym I get this when I add the resolver you mentioned and switch to the 2.12 snapshot:
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang.modules#scala-xml_2.12.0-3ecc141-nightly;1.0.5: not found
[warn]  :: org.scala-lang.modules#scala-parser-combinators_2.12.0-3ecc141-nightly;1.0.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          org.scala-lang.modules:scala-xml_2.12.0-3ecc141-nightly:1.0.5
[warn]            +- org.scala-lang:scala-compiler:2.12.0-03cc6f9-SNAPSHOT (/localhome/doeraene/projects/scalajs/project/Build.scala#L477)
[warn]            +- org.scala-js:scalajs-compiler_2.12.0-03cc6f9-SNAPSHOT:0.6.8-SNAPSHOT ()
[warn]          org.scala-lang.modules:scala-parser-combinators_2.12.0-3ecc141-nightly:1.0.4
[warn]            +- org.scala-lang:scala-compiler:2.12.0-03cc6f9-SNAPSHOT (/localhome/doeraene/projects/scalajs/project/Build.scala#L477)
[warn]            +- org.scala-js:scalajs-compiler_2.12.0-03cc6f9-SNAPSHOT:0.6.8-SNAPSHOT ()
```
Is there another resolver somewhere for the nightlies of scala-xml and scala-parser-combinators that I can use?

**Comment by retronym** [comment]
@sjrd Oh sorry, you also need: https://scala-ci.typesafe.com/artifactory/scala-release-temp/

**Comment by sjrd** [comment]
OK thanks now I can resolve everything. Working on it.
