### ISSUE TITLE
testHtml{Fast,Full}Opt is broken on master

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2889]
There's a `TypeError` in the browser console:
```
TypeError: org.scalajs.testinterface.HTMLRunner is not a function
```
It was broken in facca8515a55a0969c618dc59a71a885449897da because `HTMLRunner` is actually a `js.JSApp`, and the `HTMLRunnerTemplate` relies on the *export* of the `HTMLRunner`.
