### PR TITLE
DO NOT MERGE Merge release-1.0.0 into master January 21

### LINKED ISSUE #3865: Scala.js 0.6.30 does not acknowledge IR version 0.6.29 as supported.
We forgot to reset [`binaryEmitted`](https://github.com/scala-js/scala-js/blob/0.6.x/ir/src/main/scala/org/scalajs/core/ir/ScalaJSVersions.scala#L36) to `"0.6.29"`, and add `"0.6.29"` to the list of `binarySupported`.

That means that when using a library built with 0.6.29 from a 0.6.30, the deserializer complains that it does not support version 0.6.29 (although in fact it does).

This is a critical issue that makes 0.6.30 completely unusable. Unfortunately it's already on Maven Central, so we'll have to release 0.6.31 to fix it.

### LINKED ISSUE #3872: The CLI does not work with Scala 2.12.10
It crashes with a `NoSuchMethodError` in the compiler.

This happens because the CLI scripts assume that a Scala version is of the form `[0-9]\.[0-9][0-9]\.[0-9]`, i.e., the patch version number has exactly 1 digit. So it parses 2.12.10 as 2.12.1 (discarding the rest) and therefore loads `scalajs-compiler_2.12.1.jar`, which is not binary compatible with `scala-compiler.jar` v2.12.10.

I had not realized that before because I kept testing with 2.12.8 which was already installed on my test machines. And 2.11.{10-12} work because our jar for 2.11.1 happens to also work with 2.11.12.

### LINKED ISSUE #3888: Linking errors on Scala 2.11 if an `object` is named `class`
The following code works fine on Scala 2.12, but does not link on Scala 2.11:
``` scala
object `class` {
  def foo() = {
    println("Hello, World!")
  }
}

`class`.foo()
```

https://scalafiddle.io/sf/LRfrjg0/0

### LINKED ISSUE #3901: Regression on regex when upgrading from 0.6.28 to 0.6.31
```
// project/plugins.sbt: addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.31")
import scala.util.matching.Regex
val text = ???
val regex: String = ???
val it: Iterator[Regex.Match] = regex.r.findAllMatchIn(text)
println(it.hasNext)  // returns true
it.next // it fails with:

TypeError: Cannot read property 'length' of null
    at $c_ju_regex_Matcher.end__I__I (RuntimeString.scala:252)
    at $c_s_util_matching_Regex$Match.ends$lzycompute__p1__AI (Regex.scala:732)
    at $c_s_util_matching_Regex$Match.ends__p1__AI (Regex.scala:731)
    at $c_s_util_matching_Regex$Match.force__s_util_matching_Regex$Match (Regex.scala:743)
    at $c_s_util_matching_Regex$$anon$1.next__s_util_matching_Regex$Match (Regex.scala:410)
    at $c_s_util_matching_Regex$$anon$1.next__O (Regex.scala:406)
```

it works by changing sbt-scalajs version from 0.6.31 to 0.6.28.

Unfortunately I cannot give the text and regex as it is proprietary and very long.
I'll try to minimize the text and regex and share it here when I have some time.

### LINKED ISSUE #3913: java.io.ByteArrayInputStream behaves differently between JS and JVM
The following snippet:

```scala
val arr = new Array[Byte](5)
val bais = new java.io.ByteArrayInputStream("abcde".getBytes)
bais.read(arr, 0, 5)
println(bais.read(arr, 0, 0))
```

Prints `-1` on the JDK11 and `0` on Scala.JS 0.6.31.

It seems the JVM implementation goes against the spec of `InputStream#read`:

> <p> If <code>len</code> is zero, then no bytes are read and
>      <code>0</code> is returned; otherwise, there is an attempt to read at
>      least one byte. If no byte is available because the stream is at end of
>     file, the value <code>-1</code> is returned; otherwise, at least one
>    byte is read and stored into <code>b</code>.

Not sure who we should be following - the spec or the implementation - but it would be nice if it did the same thing on both platforms (Haven't tried other versions of the JDK)

### LINKED ISSUE #3921: Running multiple fastOptJS causes java.lang.NoClassDefFoundError: jdk/internal/reflect/MethodAccessorImpl
Symptom:
- MethodAccessorImpl NoClassDefError happens with Scala.js 1.0.0-RC2, when compiling multiple Scala.JS projects. We have no such issue with Scala.js 0.6.x
- After rerunning fastOptJS, the compilation eventually succeeds.
- I'm using sbt 1.3.6 and JDK11. The same error happens with JDK8.

image 
- CI log: https://github.com/wvlet/airframe/runs/385008133

~It might be an issue of sbt-scalajs plugin and sbt-1.3.x's new classloader.~ (The same problem happens with sbt 1.2.8) I'll work on reproduction of this issue. 

It seems the reflection call of PathOutputFile in the LinkerImpl is failing:
```scala
    private val outputFileMethod =
      loadMethod("PathOutputFile", "atomic", classOf[LinkerOutput.File], classOf[Path])
```
This is used here:
```scala
            val out = LinkerOutput(linkerImpl.outputFile(output.toPath))
              .withSourceMap(linkerImpl.outputFile(sourceMapFile.toPath)) <--------
              .withSourceMapURI(relURI(sourceMapFile.getName))
              .withJSFileURI(relURI(output.getName))
```

A workaround is splitting an aggregated project into a smaller set of projects and running fastOptJS individually.

### LINKED ISSUE #3922: Wrong maxBytesPerChar for CharsetEncoder
The [auxiliary constructor](http://github.com/scala-js/scala-js/blob/69935b2781e5e8e249491d2483e1abcc42d9c877/javalib/src/main/scala/java/nio/charset/CharsetEncoder.scala#L25) of `CharsetEncoder` ignores its `_maxBytesPerChar` argument.

The line
```this(cs, _averageBytesPerChar, _averageBytesPerChar, Array('?'.toByte))```
should probably be
```this(cs, _averageBytesPerChar, _maxBytesPerChar, Array('?'.toByte))```

### LINKED ISSUE #3924: isAssignableFrom differences on 1.0.0-RC2
While trying to make shapeless work with java 1.0.0-RC2 I found a case where the JVM and JS 0.6.x behaves the same but 1.0.0-RC2 don't.
for `Character` and `Long` this operations returns `true` in 0.6 and `false` in 1.0
```
    val c: Any = 'c'
    classOf[java.lang.Character].isAssignableFrom(c.getClass)}
```
The following repo contains a bit more code
https://github.com/cquiroz/assignable

/cc @milessabin

### LINKED ISSUE #3926: Invalid ES6 produced when emitting function that returns js.Dynamic.literal
Code:
```scala
package tutorial.webapp

import scala.scalajs.js

object TutorialApp {
  def main(args: Array[String]): Unit = {
    println(() => js.Dynamic.literal(x = 123))
  }
}
```

To reproduce, run `sbt run` with this code in the tutorial app, fails with `SyntaxError: Unexpected token ':'`.

Scala.js version: 1.0.0-RC2
Scala version: 2.12.10 (interestingly, the bug **does not appear when using 2.13**)

Relevant emitted JS:
```js
const x = new $c_sjsr_AnonFunction0(((this$1) => (() => {
  "x": 123
}))(this));
```

Which fails to parse because the `{` is interpreted as opening the function body. One way that this could be fixed would be to emit parentheses around the value so it would look like

```js
const x = new $c_sjsr_AnonFunction0(((this$1) => (() => ({
  "x": 123
})))(this));

### LINKED ISSUE #3933: 1.0.0-RC2: using arg as argument name creates IR error
I cannot pinpoint the issue here but this code:

```scala
  val sfc = SFC1[Props] { arg =>
    val cond = arg.summary.facets.headOption.map(f => convertCondition(f.label)).orUndefined
    val props = new ReactWeatherDisplayProps {
      temperature = arg.summary.temp
      currentTemperature = arg.summary.temp
      width = 150
      height = 150
      condition = cond
      currentCondition = cond
    }
    div(new DivProps {
      className = "daily"
      style = layout
    })(
      Label(labelProps)(arg.summary.dateStr),
      ReactWeatherDisplay(props)
    )
  }
```

gives an IR error

```sh
[info] Fast optimizing /home/me/proj/workspace/scalajs-reaction/examples/target/scala-2.13/Scala.js
[error] file:/home/me/proj/workspace/scalajs-reaction/examples/src/main/scala/atmoache/atmoache.scala(134:21:VarDef): Duplicate local variable name arg$1.
[error] There were 1 IR checking errors.
[error] (examples / Compile / fastOptJS) There were 1 IR checking errors.
```

If a change arg to argx it compiles fine.

### PR DESCRIPTION
**Pull request by gzm0**
```
$ git checkout -b merge-release-1.0.0-into-master-january-21
Switched to a new branch 'merge-release-1.0.0-into-master-january-21'
```

```
$ export mb=$(git scala-js/release-1.0.0 scala-js/master)
$ git log --graph --oneline --decorate $mb..scala-js/release-1.0.0 | cat
*   c53faae28 (origin/merge-0.6.x-into-release-1.0.0-january-21, merge-0.6.x-into-release-1.0.0-january-21) Merge '0.6.x' into 'release-v1.0.0'
|\  
| *   1303013c0 (sjrd/0.6.x, scala-js/0.6.x) Merge pull request #3934 from sjrd/fix-js-ctor-name-clash
| |\  
| | * 787033acd Fix #3933: Use fresh names everywhere in GenJSExports.
| |/  
* |   53537123e (sjrd/release-v1.0.0, scala-js/release-v1.0.0, release-v1.0.0) Merge pull request #3928 from xerial/fix-issue-3921
|\ \  
| * | a2ee8596f Fix #3921: Work around JDK-6265952: MethodAccessorImpl NoClassDefError
|/ /  
* | 4cbf1f908 Merge '0.6.x' into 'release-v1.0.0'.
|\| 
| *   6f589c2f2 Merge pull request #3930 from sjrd/fix-bais-read-with-zero-len
| |\  
| | * 5f9af7e58 Fix #3913: Make ByteArrayInputStream.read always return -1 at EOF.
| |/  
| *   dcf288507 Merge pull request #3923 from sjrd/fix-charset-heuristic-properties
| |\  
| | * df335fc3e Fix #3922: Fix all the heuristic properties of `Charset`s.
| |/  
| *   368e57cfa Merge pull request #3916 from mliarakos/feature/javalib-consumer
| |\  
| | * 7fd9ebba8 Implement `java.util.function.Consumer`.
| |/  
| * 91e807b9e Add new methods in js.Object
* | 78175b509 Skip the no-master commit 976d20faa.
|\| 
| *   7abe034a7 Merge pull request #3910 from sjrd/disable-phantomjs-test-suite-on-ci
| |\  
| | * 976d20faa [no-master] Disable testing the test suite with PhantomJS on the CI.
* | | 8c9a5342e Merge '0.6.x' into 'release-v1.0.0'.
|\| | 
| * |   75d8244dd Merge pull request #3907 from sjrd/fix-regex-start-end-regression-3901
| |\ \  
| | |/  
| |/|   
| | * 602005ded Fix #3901: Do not fill `groupStartMap` for non-matching groups.
| |/  
* | 421d42dd8 Skip version commits and no-master commits.
|\| 
| *   de9fa18c3 Merge pull request #3909 from sjrd/disable-stacktracetest-in-bootstrap
| |\  
| | * cbd262db9 [no-master] Work around #3908: Disable StackTraceTest in bootstrap.
| |/  
| *   3d0e4e3f3 Merge pull request #3890 from sjrd/fix-nested-object-named-class
| |\  
| | * 36a92e3ff Fix #3888: Always identify impl classes by their IMPLCLASS flag.
| |/  
| * 6dbc8beb4 Towards 0.6.32.
| * 29b644013 (tag: v0.6.31) Version 0.6.31.
| *   91b554646 Merge pull request #3873 from sjrd/fix-cli-parse-version
| |\  
| | * c19399116 [no-master] Fix #3872: Fix parsing of Scala versions in scalajsc.
| * |   7e98ae55e Merge pull request #3871 from sjrd/fix-supported-ir-versions
| |\ \  
| | |/  
| |/|   
| | * 62818633c Fix #3865: Set the emitted IR version to 0.6.29, and support 0.6.{29-30}.
| |/  
| * c6fd2a950 Towards 0.6.31.
| * d7d342159 (tag: v0.6.30) Version 0.6.30.
*   7caf032f3 Merge pull request #3929 from sjrd/fix-object-lit-in-arrow-function
|\  
| * e00742189 Fix #3926: Wrap object lit in () if alone in an arrow function.
|/  
*   7f0abd1fd Merge pull request #3925 from sjrd/fix-isassignablefrom
|\  
| * 42ec34c2c Add more tests for isAssignableFrom involving *classes*, not traits.
| * 46bb84397 Fix #3924: Fix Class.isAssignableFrom for boxed classes.
* 384ce4a16 Merge pull request #3917 from gzm0/private-wrapped-values
* 2c5a65bf9 Document that copy avoidance in toJSArray is consistent with Scala
* 10ce11f0b Make WrappedDictionary final
* f9a924b4b Make wrapped collection values private
* 2ff20a458 Use js.WrappedArray.toJSArray instead of the raw field
```

```
$ git merge --no-commit scala-js/release-v1.0.0
Auto-merging project/BinaryIncompatibilities.scala
Auto-merging linker/shared/src/main/scala/org/scalajs/linker/backend/javascript/Printers.scala
Auto-merging linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/JSGen.scala
Auto-merging linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala
CONFLICT (content): Merge conflict in linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala
Auto-merging linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala
Auto-merging linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/ClassEmitter.scala
Auto-merging assets/additional-doc-styles.css
CONFLICT (content): Merge conflict in assets/additional-doc-styles.css
Automatic merge failed; fix conflicts and then commit the result.
```

Fix trivial conflicts

```
$ git commit
[merge-release-1.0.0-into-master-january-21 04a5a94bf] Merge 'release-1.0.0' into 'master'
```

### CODE REVIEW

**Comment by gzm0** [comment]
Depends on #3935 (yes, some things in the log are white lies).

**Comment by gzm0** [comment]
Superseded by #3937.
