### ISSUE TITLE
The CLI does not work with Scala 2.12.10

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3872]
It crashes with a `NoSuchMethodError` in the compiler.

This happens because the CLI scripts assume that a Scala version is of the form `[0-9]\.[0-9][0-9]\.[0-9]`, i.e., the patch version number has exactly 1 digit. So it parses 2.12.10 as 2.12.1 (discarding the rest) and therefore loads `scalajs-compiler_2.12.1.jar`, which is not binary compatible with `scala-compiler.jar` v2.12.10.

I had not realized that before because I kept testing with 2.12.8 which was already installed on my test machines. And 2.11.{10-12} work because our jar for 2.11.1 happens to also work with 2.11.12.

**Comment by sjrd** [comment]
Fixed in c1939911658403478e7adf23c628cd42cfef0e70.
