### ISSUE TITLE
The build is broken on Windows

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3324]
Trying to load the build on the master branch on Windows causes the following errors:
```
[info] Compiling 142 Scala sources to C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\classes...
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                 ^
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                       ^
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                            ^
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                                      ^
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                                              ^
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                                                      ^
[error] C:\Users\Sepi\Documents\Projets\scalajs\project\target\scala-2.10\sbt-0.13\src_managed\main\ScalaJSEnvHolder.scala:1204: invalid escape character
[error]           final val sourceMapPath = new URI("C:\Users\Sepi\Documents\Projets\scalajs\linker\scalajsenv.js")
[error]                                                                                             ^
[error] 7 errors found
[error] (compile:compileIncremental) Compilation failed
```
Clearly caused by e85e50883c0c9ed307de78c46be84a9dc1f650a1
