### PR TITLE
Fix #2285: Adapt to 2.12 trait encoding (removal of impl classes).

### LINKED ISSUE #2285: Adapt to Scala 2.12 trait encoding (removal of impl classes)
We've just run a community build against my pull request, https://github.com/scala/scala/pull/5003, that changes the Scala 2.12 trait encoding.

I was pleasantly surprised to find that everything worked... well everything other than Scala JS.

Here are the compile failure, related to methods I've removed about impl classes.

```
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:240: value IMPL_CLASS_SUFFIX is not a member of object GenJSCode.this.global.nme
[scala-js] [error]                 sym.owner.info.decl(sym.name.dropRight(nme.IMPL_CLASS_SUFFIX.length)).tpe)
[scala-js] [error]                                                            ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:240: value IMPL_CLASS_SUFFIX is not a member of object GenJSCode.this.global.nme
[scala-js] [error]                 sym.owner.info.decl(sym.name.dropRight(nme.IMPL_CLASS_SUFFIX.length)).tpe)
[scala-js] [error]                                                            ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:1056: value implClass is not a member of GenJSCode.this.global.Symbol
[scala-js] [error]             val implClassSym = sym.owner.implClass
[scala-js] [error]                                          ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala:1056: value implClass is not a member of GenJSCode.this.global.Symbol
[scala-js] [error]             val implClassSym = sym.owner.implClass
[scala-js] [error]                                          ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala:189: value isImplClassName is not a member of object JSEncoding.this.global.nme
[scala-js] [error]     sym.isModuleClass && nme.isImplClassName(sym.name)
[scala-js] [error]                              ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala:189: value isImplClassName is not a member of object JSEncoding.this.global.nme
[scala-js] [error]     sym.isModuleClass && nme.isImplClassName(sym.name)
[scala-js] [error]                              ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/TypeKinds.scala:238: value interfaceName is not a member of object TypeKinds.this.global.tpnme
[scala-js] [error]         val traitSym = sym.owner.info.decl(tpnme.interfaceName(sym.name))
[scala-js] [error]                                                  ^
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-js-07830e1e11ee5f72b4b2d29aed7bb635b8f67ae2/compiler/src/main/scala/org/scalajs/core/compiler/TypeKinds.scala:238: value interfaceName is not a member of object TypeKinds.this.global.tpnme
[scala-js] [error]         val traitSym = sym.owner.info.decl(tpnme.interfaceName(sym.name))
[scala-js] [error]                                                  ^
```

You can experiment with this build with [2.12.0-03cc6f9-SNAPSHOT](https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/scala-compiler/2.12.0-03cc6f9-SNAPSHOT/) from `"pr-scala snapshots" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"`

Would you be willing to adapt to these changes on a 2.12.x branch of ScalaJS?

### PR DESCRIPTION
**Pull request by sjrd**
The main changes are actually related to keeping source compatibility with older versions, through more compat hacks.

Also:
* Use `isTraitOrInterface` instead of `isInterface` to identify something that should be an interface at the IR level.
* A method is abstract iff its body is `EmptyTree`.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @retronym, please.

**Comment by sjrd** [comment]
Nightly for this PR: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/3771/

**Comment by gzm0** [comment]
Do we have no stack trace tests at all? (Otherwise I will of course ask you to add one for default methods :P)

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala [hunk 1]
```diff
@@ -27,6 +27,14 @@ trait Compat210Component {
...
 
     def isLocalToBlock: Boolean = self.isLocal
+
+    def implClass: Symbol = NoSymbol
+
+    /** The real implementation from 2.12.0-M4 is `isTrait || isInterface`,
+     *  but we use this method in places where, previously, we had only
+     *  `isInterface`.
+     */
+    def isTraitOrInterface: Boolean = self.isInterface
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: How hard is it to write an assertion that no one calls this from PrepJSInterop? IIUC, the method would not do the same in 2.11 and 2.12, there, right?

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala [hunk 2]
```diff
@@ -584,7 +584,7 @@ abstract class GenJSCode extends plugins.PluginComponent
         parent <- sym.info.parents
         typeSym = parent.typeSymbol
         _ = assert(typeSym != NoSymbol, "parent needs symbol")
-        if (typeSym.isInterface)
+        if (typeSym.isTraitOrInterface)
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Can you get rid of the parens while you are here?

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala [hunk 3]
```diff
@@ -58,6 +66,25 @@ trait Compat210Component {
     }
   }
 
+  // Impl classes disappeared in 2.12.0-M4
+
+  lazy val scalaUsesImplClasses: Boolean =
+    definitions.SeqClass.implClass != NoSymbol // a trait we know has an impl class
+
+  implicit final class StdTermNamesCompat(self: global.nme.type) {
+    val IMPL_CLASS_SUFFIX = "$class"
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: Could you make this a `def` and make it throw?

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala [hunk 4]
```diff
@@ -58,6 +66,25 @@ trait Compat210Component {
...
+
+    def isImplClassName(name: Name): Boolean =
+      name.endsWith(IMPL_CLASS_SUFFIX)
+  }
+
+  implicit final class StdTypeNamesCompat(self: global.tpnme.type) {
+    val IMPL_CLASS_SUFFIX = "$class"
+
+    def interfaceName(implname: Name): TypeName =
+      implname.dropRight(IMPL_CLASS_SUFFIX.length).toTypeName
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: Same here.

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala [hunk 5]
```diff
@@ -1048,8 +1048,9 @@ abstract class GenJSCode extends plugins.PluginComponent
         if (scalaPrimitives.isPrimitive(sym) &&
             !jsPrimitives.shouldEmitPrimitiveBody(sym)) {
           None
-        } else if (sym.isDeferred || sym.owner.isInterface) {
-          val body = if (sym.hasAnnotation(JavaDefaultMethodAnnotation)) {
+        } else if (rhs == EmptyTree) {
+          val body = if (scalaUsesImplClasses &&
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Replace `scalaUsesImplClasses` with `sym.implClass != NoSymbol`?

Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Hmmm... I guess you can keep it. I was trying to lure you into getting rid of `scalaUsesImplClasses`. But the other usage is really hard to replace :P

**Comment by sjrd** [comment]
> Do we have no stack trace tests at all? (Otherwise I will of course ask you to add one for default methods :P)

They come with the second commit, for free ;-)

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala (hunk 1 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: I don't understand. Could you elaborate?

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala (hunk 3 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: No, because it is used at https://github.com/sjrd/scala-js/blob/scalac-no-impl-class/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L240

File: compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala [hunk 6]
```diff
@@ -148,12 +148,15 @@ trait JSEncoding extends SubComponent { self: GenJSCode =>
 
     def name = encodeMemberNameInternal(sym)
 
+    def privateSuffix: String =
+      if (sym.owner.isTraitOrInterface) encodeClassFullName(sym.owner)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala]: We'll get plenty of tests like that for free with 2.12.0-M4. I did hit bugs, and that's how I found out I had to change this.

We cannot test this before 2.12.0-M4 because nothing can ever generate a *private* default methods.

Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala]: Ok. If you did hit bugs, then just 2.12.0-M4 is fine.

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala [hunk 7]
```diff
@@ -58,6 +66,25 @@ trait Compat210Component {
...
+  // Impl classes disappeared in 2.12.0-M4
+
+  lazy val scalaUsesImplClasses: Boolean =
+    definitions.SeqClass.implClass != NoSymbol // a trait we know has an impl class
+
+  implicit final class StdTermNamesCompat(self: global.nme.type) {
+    val IMPL_CLASS_SUFFIX = "$class"
+
+    def isImplClassName(name: Name): Boolean =
+      name.endsWith(IMPL_CLASS_SUFFIX)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: It certainly should, in practice.

What I did in general in this PR was to follow the overall "contract" of `Compat210` to maintain the same API with the same behavior over a large set of versions. Which led me to "re-implement" some functionality that was lost in upstream.

In this case, it's probably also valid to reimplement differently those methods, knowing no impl class ever exists when those come in. It's a slightly different way of looking at `Compat210`, which is probably equally valid.

I guess your preference goes to the second "contract"? I don't have any strong opinion on this.

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala (hunk 5 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Yep :-p I was disappointed I had to resort to this lazy val.

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala (hunk 3 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: Although that line is protected by `isImplClass`, so in fact it would be fine. So again, it all depends on the decision about https://github.com/scala-js/scala-js/pull/2288/files#r55755629

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala (hunk 1 above)
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: If somebody (in the future), uses this method in PrepJSInterop (or any phase pre-mixin for that matter) and expects it to return `isTrait || isInterface` (which exists pre-2.12 IIUC), this will work in 2.12. However, in pre-2.12, this test will fail for traits that have implementations. (Btw. why can't you just implement this with `self.isInterface || self.isTrait`?)

Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: > Btw. why can't you just implement this with self.isInterface || self.isTrait?

Er ... I didn't try ^^ I probably can, indeed. -_-'

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala (hunk 7 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: OK I'll change that, then.

**Comment by sjrd** [comment]
!! 623 - run/t6443.scala                           [compilation failed]

failed in two jobs, so it's probably not spurious

File: compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala (hunk 1 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/Compat210Component.scala]: It works just as well, so I'll take that.

**Comment by sjrd** [comment]
> run/t6443.scala

scalac gives us this absurd tree after mixin in 2.11.7:
```scala
  abstract trait A extends Object {
    <accessor> def helloworld$A$_setter_$s_=(x$1: String): Unit;
    def foo(d: String, d2: String): helloworld.Base = {
  <synthetic> val d2$1: String = (d2: String);
  <empty>
}.$asInstanceOf[helloworld.Base]();
    <stable> <accessor> def s(): String;
    def bar(): Unit
  };
```
Note that `A` is an interface, yet it has a method (`foo`) with a non-empty body, but that body, inside, contains an `<empty>`, which causes the blow up ...

**Comment by sjrd** [comment]
@gzm0 Updated with your comments + fix run/t6443.scala (there's a comment).

**Comment by retronym** [comment]
@sjrd I can confirm that this branch builds successfully in a [run of Scala community build](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/340/console) using the new trait encoding.

**Comment by retronym** [comment]
This patch LGTM, too, although I'm not familiar enough with ScalaJS to offer more than a superficial review.

**Comment by sjrd** [comment]
@retronym Thanks! I had to re-change the `privateSuffix` thing so that impl classes in 2.10 and 2.11 don't receive the full class name to fix the CI failure (we have a test asserting that the generated .js file does not grow). I did retest on the 2.12 temporary build, but maybe it deserves another community build to be safe.

@gzm0 Would you have time to have a second look today, please?

**Comment by gzm0** [comment]
LGTM

**Comment by sjrd** [comment]
New nighlty build: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/3776/

**Comment by sjrd** [comment]
Nightly passed :-)
